---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }}
  name: caddyfile
data:
  Caddyfile: |
    :2015 {
        @ws {
            header Upgrade websocket
        }
        reverse_proxy 35.183.15.35:8021
        reverse_proxy @ws 35.183.15.35:8022
    }