---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }}
  name: caddyfile
data:
  Caddyfile: |
    :2015 {
        @ws {
            header Upgrade websocket
        }
        reverse_proxy agent:8021
        reverse_proxy @ws agent:8022
    }