{{- with .Values.agent }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}-env
type: Opaque
stringData:
  ACAPY_WALLET_SEED: '{{ .environment.ACAPY_WALLET_SEED }}'
  ACAPY_WALLET_KEY: '{{ .environment.ACAPY_WALLET_SEED }}'
{{- end }}