{{- with .Values.agent }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    {{- range .service_ports }}
    - protocol: TCP
      name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
{{- end }}