---
namespace: dtt-vc-api
app_domain: "dtt.idlab.app"

vc_api:
  name: vc-api
  image: idlaborg/dtt-vc-api:0.0.83
  service_ports:
  - name: api
    port: 8000
    targetPort: 8000
  ingress:
  - host: vc-api.dtt.idlab.app
    port: 8000
  environment:
    VC_API_ENDPOINT: https://vc-api.dtt.idlab.app
    AGENT_ADMIN_ENDPOINT: http://35.183.15.35:8020
    AGENT_VERKEY: GM5aqC8Ka4XaAHdvZ4NeqUuPKXCpD5rArynkDQeFKmU3
    AGENT_DID: VA56jZQD1V8dvhzD6vBqP4
    AGENT_KEY_TYPE: ed25519
    AGENT_METHOD: key

caddy:
  name: caddy
  image: caddy
  service_ports:
  - name: caddy
    port: 2015
    targetPort: 2015
  ingress:
  - host: agent.dtt.idlab.app
    port: 2015

# agent:
#   name: agent
#   image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.9.0
#   service_ports:
#   - name: admin
#     port: 8020
#     targetPort: 8020
#   - name: inbound-http
#     port: 8021
#     targetPort: 8021
#   - name: inbound-ws
#     port: 8022
#     targetPort: 8022
#   ingress:
#   - host: agent-admin.dtt.idlab.app
#     port: 8020
#   environment:
#     ACAPY_LOG_LEVEL: info
#     ACAPY_LABEL: IDLab DTT Bench
#     ACAPY_ADMIN: '["0.0.0.0", "8020"]'
#     ACAPY_ENDPOINT: https://agent.dtt.idlab.app
#     ACAPY_IMAGE_URL: https://vc.dtt.idlab.app/logo
#     ACAPY_NO_LEDGER: False
#     ACAPY_GENESIS_URL: https://raw.githubusercontent.com/bcgov/von-network/main/BCovrin/genesis_test
#     ACAPY_WALLET_TYPE: askar
#     ACAPY_INBOUND_TRANSPORT: '[["http", "0.0.0.0", "8021"], ["ws", "0.0.0.0", "8022"]]'
#     ACAPY_OUTBOUND_TRANSPORT: '["http", "ws"]'
#     ACAPY_WALLET_KEY: change_me
#     ACAPY_WALLET_SEED: idlab_vc-api_demo-00000000000000
